apiVersion: v1
kind: Namespace
metadata:
  name: aden-chatbot
---
apiVersion: v1
kind: Secret
metadata:
  namespace: aden-chatbot
  name: aden-chatbot
type: Opaque
data:
  OPENAI_API_KEY: <base64 encoded key>
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: aden-chatbot
  name: aden-chatbot
  labels:
    app: aden-chatbot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aden-chatbot
  template:
    metadata:
      labels:
        app: aden chatbot
    spec:
      containers:
        - name: aden-chatbot
          image: <docker user>/aden-chatbot:latest
          resources: {}
          ports:
            - containerPort: 3000
          env:
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: aden-chatbot
                  key: OPENAI_API_KEY
---
kind: Service
apiVersion: v1
metadata:
  namespace: aden-chatbot
  name: aden-chatbot
  labels:
    app: aden-chatbot
spec:
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3000
  selector:
    app: aden-chatbot
  type: ClusterIP
